from . import DaySplitURLS
from . import ExerciseEquipmentURLS
from . import ExerciseRoutineTemplateURLS
from . import ExerciseTypeURLS
from . import ExerciseURLS
from . import ExerciseVariantURLS
from . import GenderURLS
from . import MuscleDayURLS
from . import MuscleURLS
from . import RoutineTemplateURLS
from . import RoutineURLS
from . import SerieURLS
from . import SplitURLS
from . import SplitUserURLS
from . import UserURLS
from . import WeightUnitURLS